# This file was generated by the owner-gated release pipeline.
cask "aim" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "c67df394ec28c339be87d0c85ba5b736bec2d7c4c6a033582ec4e5ee5126e386"
      url "https://github.com/adrijshikhar/aim/releases/download/v#{version}/aim_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f873a72ea86845ceb06301a6d68395bcd487d42285ae0e8b1e14b33bc65622d"
      url "https://github.com/adrijshikhar/aim/releases/download/v#{version}/aim_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "83befc306abea487c07e2878f8abe01d0bd8e2328372b2bcbbe68020e92cb6a3"
      url "https://github.com/adrijshikhar/aim/releases/download/v#{version}/aim_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "335fc8f1437ad33f95f4a2ed11be82ad096648e9f1036ade7286c6da5b78a77c"
      url "https://github.com/adrijshikhar/aim/releases/download/v#{version}/aim_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aim"
  desc "Isolated Profile Manager for AI Agents (Antigravity, Claude Code, Codex, Gemini)"
  homepage "https://github.com/adrijshikhar/aim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aim"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aim"]
    end
  end
end
