# This file was generated by the owner-gated release pipeline.
cask "aim" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "8268e0051a5dbda5a1163ddb67d7138b7da3c869b604c1caa28b3f65a7db5c6c"
      url "https://github.com/adrijshikhar/aim/releases/download/v#{version}/aim_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "577c967fd125fc37bc7e53554ced8630e5a03796f94a7f8f5830eb1d8a1aae46"
      url "https://github.com/adrijshikhar/aim/releases/download/v#{version}/aim_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bf40274a9b36336daf0b62d974addb45f03586311f03f3657ecd913fe8f6f0e9"
      url "https://github.com/adrijshikhar/aim/releases/download/v#{version}/aim_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "78e8a6f26ab08149952bbd51198a337f4ea33a0a8d9d272edea8bae3c70a1d79"
      url "https://github.com/adrijshikhar/aim/releases/download/v#{version}/aim_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aim"
  desc "Isolated Profile Manager for AI Agents (Antigravity, Claude Code, Codex, Gemini)"
  homepage "https://github.com/adrijshikhar/aim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aim"
end
