# This file was generated by the owner-gated release pipeline.
cask "aim" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "48cf3784de60207638bcf23c64ec2d9624452eb7a3bcc9cd59692caeea9a85f7"
      url "https://github.com/adrijshikhar/aim/releases/download/v#{version}/aim_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0b55b6886eae3957e54d4487e2b9f1b5be18707c7b08288127f4cf5bcfa822bf"
      url "https://github.com/adrijshikhar/aim/releases/download/v#{version}/aim_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5c5617ae81b71618238822917568c6fe84266b98e81c3a12e6c034e568e0e075"
      url "https://github.com/adrijshikhar/aim/releases/download/v#{version}/aim_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "68aee725f6b7cc0f8c778acca206a52366f2248f5d6da5699d1d5bd3974131a8"
      url "https://github.com/adrijshikhar/aim/releases/download/v#{version}/aim_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aim"
  desc "Isolated Profile Manager for AI Agents (Antigravity, Claude Code, Codex, Gemini)"
  homepage "https://github.com/adrijshikhar/aim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aim"
end
