# This file was generated by GoReleaser. DO NOT EDIT.
cask "binsight" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "9b7c2cbb515541bc76ebecc4438a88626ef6238defd2b8809eeeab46d2850533"
      url "https://github.com/adrijshikhar/binsight/releases/download/v#{version}/binsight_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "80bf3a6e6582d6004b6e4deaddf1f5dbc0327c0f5af1877407137a9caeb25337"
      url "https://github.com/adrijshikhar/binsight/releases/download/v#{version}/binsight_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "62e7dca05b3d480b292d0504534e2e1b85864a3eec2a02a97a359bd26cd7dcea"
      url "https://github.com/adrijshikhar/binsight/releases/download/v#{version}/binsight_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d7835f2a270e96c2c148ae0947752a874e7b64b9822495066ff6f328185a66e"
      url "https://github.com/adrijshikhar/binsight/releases/download/v#{version}/binsight_#{version}_linux_arm64.tar.gz"
    end
  end

  name "binsight"
  desc "A local MySQL & MariaDB binlog viewer and analyzer for developers"
  homepage "https://github.com/adrijshikhar/binsight"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "binsight"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/binsight"]
    end
  end

  # No zap stanza required

end
