# This file was generated by GoReleaser. DO NOT EDIT.
cask "binsight" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "e041c30fb2278d9b8f338676f7797133ff0f628ad30d3e7ffaa6c9e36f896882"
      url "https://github.com/adrijshikhar/binsight/releases/download/v#{version}/binsight_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c5d5accd81726969361c0f9e1ce2210fd66f485eb79db73dda1617e6a1d4fb9c"
      url "https://github.com/adrijshikhar/binsight/releases/download/v#{version}/binsight_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e390e18ea15f2c29c4e924f8555baa8110a2e6d0e5f91aa1a6247d55fa03dbb6"
      url "https://github.com/adrijshikhar/binsight/releases/download/v#{version}/binsight_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea5ad6511899fedccaf918e660ff71c5ac37cd5ddc508de77597f594a5af776b"
      url "https://github.com/adrijshikhar/binsight/releases/download/v#{version}/binsight_#{version}_linux_arm64.tar.gz"
    end
  end

  name "binsight"
  desc "A local MySQL & MariaDB binlog viewer and analyzer for developers"
  homepage "https://github.com/adrijshikhar/binsight"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "binsight"

  # No zap stanza required

end
