# This file was generated by GoReleaser. DO NOT EDIT.
cask "binsight" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "d742978b38111db114334126386c1828194808671eec9d21ae9650f1e9a21b62"
      url "https://github.com/adrijshikhar/binsight/releases/download/v#{version}/binsight_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a3a8cc56281987d462af7631acb32f5ce0a1078655bd748fb04f976fe75cbdee"
      url "https://github.com/adrijshikhar/binsight/releases/download/v#{version}/binsight_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "01f888ce087554c9acf462000905142c237a60476c12aa9ecc4bdef2196cba65"
      url "https://github.com/adrijshikhar/binsight/releases/download/v#{version}/binsight_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "33971004983a5a7e095cce85cea1ab6306be3daf6ed4b666e203a420664bfc92"
      url "https://github.com/adrijshikhar/binsight/releases/download/v#{version}/binsight_#{version}_linux_amd64.tar.gz"
    end
  end

  name "binsight"
  desc "A local MySQL & MariaDB binlog viewer and analyzer for developers"
  homepage "https://github.com/adrijshikhar/binsight"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "binsight"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/binsight"]
    end
  end

  # No zap stanza required
end
